
plot_vars_titles = {
    'weight':['weight','weight','# events'],
    'met_pt':['MET','MET (GeV)','# events'], 
    'met_phi':['MET_phi','MET phi','# events'], 
    'metnomu_pt':['METNoMu','METNoMu (GeV)','# events'], 
    'metnomu_phi':['METNoMu_phi','METNoMu phi','# events'], 
    'nsv':['nSV','nSV','# events'], 
    'nbtag_jet':['nbtag_jet','number of b-tagged jets','# events'],
    'MLScore':['MLScore','MLScore','# events'],
    'vtx_ntk':['vtx_ntk','nTracks/SV','# events'],
    'vtx_dBV':['vtx_dBV','dist2d(SV, beamspot) (cm)','# events'],
    'vtx_dBVerr':['vtx_dBVerr','error dist2d(SV, beamspot) (cm)','# events'],
    'vtx_mass_track':['vtx_mass_track','SV tracks-only mass (GeV)','# events'],
    'vtx_mass_jet':['vtx_mass_jet','SV jets-by-ntracks -only mass (GeV)','# events'],
    'vtx_mass_trackjet':['vtx_mass_trackjet','SV tracks-plus-jets-by-ntracks mass (GeV)','# events'],
    'vtx_tk_pt':['vtx_tk_pt','all SV tracks pT (GeV)','# events'], 
    'vtx_tk_eta':['vtx_tk_eta','all SV tracks eta','# events'], 
    'vtx_tk_phi':['vtx_tk_phi','all SV tracks phi','# events'],
    'vtx_tk_dxy':['vtx_tk_dxy','all SV tracks dxybs (cm)','# events'],
    'vtx_tk_dxy_err':['vtx_tk_dxy_err','all SV tracks err(dxybs) (cm)','# events'],
    'vtx_tk_nsigmadxy':['vtx_tk_nsigmadxy','all SV tracks nsigma(dxybs)','# events'],
    'vtx_tk_dz':['vtx_tk_dz','all SV tracks dz (cm)','# events'],
    'vtx_tk_dz_err':['vtx_tk_dz_err','all SV tracks err(dz) (cm)','# events'],
    'vtx_tk_nsigmadz':['vtx_tk_nsigmadz','all SV tracks nsigma(dz)','# events'],
    'jet_pt':['jet_pt','jet pT (GeV)','# events'],
    'jet_eta':['jet_eta','jet eta','# events'],
    'jet_phi':['jet_phi','jet phi','# events'],
    'jet_ntrack':['jet_ntrack','jet nTrack','# events'],
    'jet_btag':['jet_btag','jet btag','# events'],
    'jet_flavor':['jet_flavor','jet flavor','# events'],
    'tk_pt':['tk_pt','track pT (GeV)','# events'],
    'tk_eta':['tk_eta','track eta','# events'],
    'tk_phi':['tk_phi','track phi','# events'],
    'tk_dxybs':['tk_dxybs','track dxybs (cm)','# events'],
    'tk_dxybs_sig':['tk_dxybs_sig','track nsigma(dxybs)','# events'],
    'tk_dxybs_err':['tk_dxybs_err','track err(dxybs) (cm)','# events'],
    'tk_dz':['tk_dz','track dz (cm)','# events'],
    'tk_dz_sig':['tk_dz_sig','track nsigma(dz)','# events'],
    'tk_dz_err':['tk_dz_err','track err(dz) (cm)','# events'],
    'n_gen_bquarks':['n_gen_bquarks','number of gen b-quarks','# events'],
    'gen_bquarks_pt':['gen_bquarks_pt','gen bquark pT (GeV)','# events'],
    'gen_bquarks_eta':['gen_bquarks_eta','gen bquarks eta','# events'],
    'gen_bquarks_phi':['gen_bquarks_phi','gen bquarks phi','# events'],
}

# variables that each event has only one value
plot_vars_single = {
    'weight':['weight','weight','# events'],
    'met_pt':['MET','MET (GeV)','# events'], 
    'met_phi':['MET_phi','MET phi','# events'], 
    'metnomu_pt':['METNoMu','METNoMu (GeV)','# events'], 
    'metnomu_phi':['METNoMu_phi','METNoMu phi','# events'], 
    'nsv':['nSV','nSV','# events'], 
    'nbtag_jet':['nbtag_jet','number of b-tagged jets','# events'],
    'MLScore':['MLScore','MLScore','# events'],
    'vtx_ntk':['vtx_ntk','nTracks/SV','# events'],
    'vtx_dBV':['vtx_dBV','dist2d(SV, beamspot) (cm)','# events'],
    'vtx_dBVerr':['vtx_dBVerr','error dist2d(SV, beamspot) (cm)','# events'],
    'vtx_mass_track':['vtx_mass_track','SV tracks-only mass (GeV)','# events'],
    'vtx_mass_jet':['vtx_mass_jet','SV jets-by-ntracks -only mass (GeV)','# events'],
    'vtx_mass_trackjet':['vtx_mass_trackjet','SV tracks-plus-jets-by-ntracks mass (GeV)','# events'],
    'n_gen_bquarks':['n_gen_bquarks','number of gen b-quarks','# events'],
}

# variables that each event has possibly more than one value
plot_vars_multi = {
    'jet_pt':['jet_pt','jet pT (GeV)','# events'],
    'jet_eta':['jet_eta','jet eta','# events'],
    'jet_phi':['jet_phi','jet phi','# events'],
    'jet_ntrack':['jet_ntrack','jet nTrack','# events'],
    'jet_btag':['jet_btag','jet btag','# events'],
    'jet_flavor':['jet_flavor','jet flavor','# events'],
    'tk_pt':['tk_pt','track pT (GeV)','# events'],
    'tk_eta':['tk_eta','track eta','# events'],
    'tk_phi':['tk_phi','track phi','# events'],
    'tk_dxybs':['tk_dxybs','track dxybs (cm)','# events'],
    'tk_dxybs_sig':['tk_dxybs_sig','track nsigma(dxybs)','# events'],
    'tk_dxybs_err':['tk_dxybs_err','track err(dxybs) (cm)','# events'],
    'tk_dz':['tk_dz','track dz (cm)','# events'],
    'tk_dz_sig':['tk_dz_sig','track nsigma(dz)','# events'],
    'tk_dz_err':['tk_dz_err','track err(dz) (cm)','# events'],
    'vtx_tk_pt':['vtx_tk_pt','all SV tracks pT (GeV)','# events'], 
    'vtx_tk_eta':['vtx_tk_eta','all SV tracks eta','# events'], 
    'vtx_tk_phi':['vtx_tk_phi','all SV tracks phi','# events'],
    'vtx_tk_dxy':['vtx_tk_dxy','all SV tracks dxybs (cm)','# events'],
    'vtx_tk_dxy_err':['vtx_tk_dxy_err','all SV tracks err(dxybs) (cm)','# events'],
    'vtx_tk_nsigmadxy':['vtx_tk_nsigmadxy','all SV tracks nsigma(dxybs)','# events'],
    'vtx_tk_dz':['vtx_tk_dz','all SV tracks dz (cm)','# events'],
    'vtx_tk_dz_err':['vtx_tk_dz_err','all SV tracks err(dz) (cm)','# events'],
    'vtx_tk_nsigmadz':['vtx_tk_nsigmadz','all SV tracks nsigma(dz)','# events'],
    'gen_bquarks_pt':['gen_bquarks_pt','gen bquark pT (GeV)','# events'],
    'gen_bquarks_eta':['gen_bquarks_eta','gen bquarks eta','# events'],
    'gen_bquarks_phi':['gen_bquarks_phi','gen bquarks phi','# events'],
}

# variables that each event has multiple arrays
plot_vars_nestedarray = {
}
bins_dBV = [0,0.01,0.02,0.03]
bins_dBV += [i*0.04 for i in range(1,26)]
bins_MET = [i for i in range(0, 100, 10)] + [i for i in range(100, 200, 10)] + [200, 220, 240, 270, 300, 350, 400, 450, 500, 600, 700, 800, 1000]
plot_setting = {
    'weight': {'range':(0,10), 'bins':100},
    'met_pt': {'range':(0,1000), 'bins':100},
    'met_phi': {'range':(-3.2,3.2), 'bins':64},
    'metnomu_pt': {'range':(0,1000), 'bins':100},
    'metnomu_phi': {'range':(-3.2,3.2), 'bins':64},
    #'met_pt': {'binlist':array('d', bins_MET), 'range':(0,1000),'bins':len(bins_MET)},
    #'metnomu_pt': {'binlist':array('d', bins_MET), 'range':(0,1000),'bins':len(bins_MET)},
    'nsv': {'range':(0,10), 'bins':10},
    'nbtag_jet': {'range':(0,10),'bins':10},
    'MLScore': {'range':(0,2), 'bins':50},
    'vtx_ntk': {'range':(0,40), 'bins':40},
    #'vtx_dBV': {'range':(0,1), 'bins':25},
    #'vtx_dBV': {'binlist':array('d', bins_dBV), 'range':(0,1), 'bins':25},
    'vtx_dBV': {'range':(0,2.5), 'bins':100},
    'vtx_dBVerr': {'range':(0,0.05), 'bins':250},
    #'vtx_dBVerr': {'range':(0,0.05), 'bins':1000},
    'vtx_mass_track': {'range':(0,200), 'bins':25},
    'vtx_mass_jet': {'range':(0,500), 'bins':50},
    'vtx_mass_trackjet': {'range':(0,500), 'bins':50},
    'vtx_tk_pt': {'range':(0,200), 'bins':50},
    'vtx_tk_eta': {'range':(-4,4), 'bins':50},
    'vtx_tk_phi': {'range':(-3.2,3.2), 'bins':64},
    'vtx_tk_dxy': {'range':(0,0.5), 'bins':25},
    'vtx_tk_dxy_err': {'range':(0,0.025), 'bins':25},
    'vtx_tk_nsigmadxy': {'range':(0,40), 'bins':25},
    'vtx_tk_dz': {'range':(0,20), 'bins':50},
    'vtx_tk_dz_err': {'range':(0,0.15), 'bins':50},
    'vtx_tk_nsigmadz': {'range':(0,3000), 'bins':50},
    'jet_pt': {'range':(0,500), 'bins':50},
    'jet_eta': {'range':(-4,4), 'bins':50},
    'jet_phi': {'range':(-3.2,3.2), 'bins':64},
    'jet_ntrack': {'range':(0,40), 'bins':40},
    'jet_btag': {'range':(0,5),'bins':5},
    'jet_flavor': {'range':(0,5), 'bins':5},
    'tk_pt': {'range':(0,500), 'bins':100},
    'tk_eta': {'range':(-4,4), 'bins':50},
    'tk_phi': {'range':(-3.2,3.2), 'bins':64},
    'tk_dxybs': {'range':(-0.5,0.5), 'bins':50},
    'tk_dxybs_sig': {'range':(-40,40), 'bins':50},
    'tk_dxybs_err': {'range':(0,0.06), 'bins':50},
    'tk_dz': {'range':(-15,15), 'bins':50},
    'tk_dz_sig': {'range':(-3000,3000), 'bins':50},
    'tk_dz_err': {'range':(0,0.1), 'bins':50},
    'n_gen_bquarks': {'range':(0,10), 'bins':10},
    'gen_bquarks_pt': {'range':(0,500), 'bins':50},
    'gen_bquarks_eta': {'range':(-4,4), 'bins':50},
    'gen_bquarks_phi': {'range':(-3.2,3.2), 'bins':64},
}
